version: '3'

services: 
    api-mocks:
        build: .
        ports: 
            - "5000:5000"
        volumes: 
            - .:/app
        environment: 
            FLASK_ENV: development
        